# this file MUST end in "aws_ec2.yaml" in order for the plugin to work
# running the below will get you the queried inventory output
# ansible-inventory -i inventory_aws_ec2.yaml --graph

# BEFORE enabling public DNS names on Terraform ec2 config
# robert@LIN-UBUNTU-02:~/git/DOB_Ansible/docker_apps$ ansible-inventory -i inventory_aws_ec2.yaml --graph
# @all:
#   |--@aws_ec2:
#   |  |--ip-10-0-1-11.ec2.internal
#   |  |--ip-10-0-1-131.ec2.internal
#   |  |--ip-10-0-1-84.ec2.internal
#   |--@ungrouped:

# AFTER enabling public DNS names on Terraform ec2 config
# robert@LIN-UBUNTU-02:~/git/DOB_Ansible/docker_apps$ ansible-inventory -i inventory_aws_ec2.yaml --graph
# @all:
#   |--@aws_ec2:
#   |  |--ec2-18-212-25-52.compute-1.amazonaws.com
#   |  |--ec2-3-92-205-6.compute-1.amazonaws.com
#   |  |--ec2-44-202-108-254.compute-1.amazonaws.com
#   |--@ungrouped:
# robert@LIN-UBUNTU-02:~/git/DOB_Ansible/docker_apps$
---
plugin: aws_ec2
region:
  - us-east-1
# filters allow targeting of specific instance(s) instead of all in the region
filters:
  tag:Name: dev*
# dynamic groups
keyed_groups:
  - key: tags
    prefix: tag
  - key: instance_type
    prefix: instance_type